### ISSUE TITLE
 trying to build ada

### ISSUE THREAD

**Issue by cyrstem** [patriciogonzalezvivo/ada#3]
hey i was trying to build ada but i got this  error im not sure how to fix it 

 97%] Building CXX object examples/CMakeFiles/hello_world.dir/hello_world.cpp.o
/home/jacos/ada/examples/hello_world.cpp: In function ‘int main(int, char**)’:
/home/jacos/ada/examples/hello_world.cpp:106:17: error: invalid initialization of reference of type ‘glm::ivec4
’ {aka ‘glm::tvec4<int, glm::packed_highp>&’} from expression of type ‘int’
  106 |     ada::initGL(argc, argv);
      |                 ^~~~
In file included from /home/jacos/ada/examples/hello_world.cpp:9:
/home/jacos/ada/include/ada/window.h:17:25: note: in passing argument 1 of ‘int ada::initGL(glm::ivec4&, ada::WindowStyle)’
   17 | int  initGL(glm::ivec4 &_viewport, WindowStyle _style = REGULAR);
      |             ~~~~~~~~~~~~^~~~~~~~~
make[2]: *** [examples/CMakeFiles/hello_world.dir/build.make:76: examples/CMakeFiles/hello_world.dir/hello_world.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:263: examples/CMakeFiles/hello_world.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

**Comment by patriciogonzalezvivo** [comment]
Sorry, very recently change that function arguments to this https://github.com/patriciogonzalezvivo/ada/blob/main/include/ada/window.h#L17

I will update that example soon. Thanks for the heads up

**Comment by patriciogonzalezvivo** [comment]
Hi @cyrstem! I just fix the example let me know how it goes!

**Comment by cyrstem** [comment]
hey @patriciogonzalezvivo  it works now !!

**Comment by patriciogonzalezvivo** [comment]
YAY!
