### ISSUE TITLE
OPENGL_opengl_LIBRARY: OPENGL_opengl_LIBRARY-NOTFOUND

### ISSUE THREAD

**Issue by theottm** [patriciogonzalezvivo/ada#4]
Hi!

This seems like a nice new project again. Looks like a promising alternative to OFX from my point of view (I used OFX just once to build a software but never digged into the rabbit hole, I'm trying to stay minimalist in my dependencies) Are there projects based on it already ?

Anyway I am also trying to package glslViewer for guix. I stumbled across a problem when compiling. It seems that the variable `OPENGL_opengl_LIBRARY` can't be defined.

The error message is
```
[...]
-- LOADING OPENGL
-- Found OpenGL: /gnu/store/5sbldxhgxwn2cjlkgak8sz1xms5paw2b-mesa-21.2.5/lib/libGL.so   
-- OPENGL_LIBRARIES: /gnu/store/5sbldxhgxwn2cjlkgak8sz1xms5paw2b-mesa-21.2.5/lib/libGL.so;/gnu/store/l5yz3h2vcs13mz71qgrrkrg5gnzds8ql-glu-9.0.1/lib/libGLU.so
-- OPENGL_opengl_LIBRARY: OPENGL_opengl_LIBRARY-NOTFOUND
[...]
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
OPENGL_opengl_LIBRARY (ADVANCED)
    linked by target "ada" in directory /tmp/guix-build-glslviewer-2.0.0.drv-0/source/deps/ada/src

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
```

I'm a bit confused because it seems that OpenGL is found. What is typically the value `OPENGL_opengl_LIBRARY` gets assigned to?

Cheers!

Théo

**Comment by patriciogonzalezvivo** [comment]
Hi Theo! yes, I'm currently porting all my programs to it. For the moment those that are public are:

* [ada_example](https://github.com/patriciogonzalezvivo/ada_example)
* [GlslViewer](https://github.com/patriciogonzalezvivo/glslViewer)

Regarding your issue, do you mind giving some context like your OS?

**Comment by theottm** [comment]
Ah nice I'll take a look at that ada examples.

The operating system I is young and kind of exotic. Its guix OS

**Comment by patriciogonzalezvivo** [comment]
Oh! I understand now. Thanks for trying to make a package for it. First time I hear about it GUIX.

So I did a bit of research and change ADA's OpenGL linking libraries in this way https://github.com/patriciogonzalezvivo/ada/commit/4190f32a4b8b110e0504d81eb7ec4031e61746ab

Do you mind giving it a go?

Thank you again

**Comment by theottm** [comment]
Hurray it worked! I just directly pinned the last commit https://github.com/patriciogonzalezvivo/glslViewer/commit/a2facb598bf4bcd736c1b53e7ca59433a9625985 on the glslViewer repo and used recursive pull of submodules.

I'll let you know once it reaches the guix distro (it might take a little while, I'm a bit bit busy with other stuff)

Thank you for the amazing work. I always enjoy hacking around using glslViewer.

I would also be curious to try building something on top of ada. I'll let you know

Happy new year!

**Comment by patriciogonzalezvivo** [comment]
Yay! I’m so glad it did! And I’m excited for the adding another distro we can support! Feel free to edit the wiki with the installation/compilation details : )

Happy new year!!
