### ISSUE TITLE
Cannot build with ffmpeg 4.0+

### ISSUE THREAD

**Issue by gnuille** [patriciogonzalezvivo/ada#8]
On rolling release distributions ffmepg 4.0+ is distributed. The function **_avcodec_decode_video2_** is deprecated therefore we are unable to build/use the program.

**Comment by irncat** [comment]
Hi Gnuille,

I have made a pull request that should fix issues with ffmpeg 4.0

**Comment by patriciogonzalezvivo** [comment]
Thank you @spikanor11 !!! note that I have to remove the `const` to make it work on older versions. Do you mind to confirm if this still works for you? Other wise I think we could use `LIBAVFORMAT_VERSION_MAJOR` from `libavformat/version.h` to fork the behavior on newer versions

**Comment by patriciogonzalezvivo** [comment]
Upgrade my `brew` formulas, bump my ffmpeg up and I'm now needing to be `const` : )
Adding a quick fix following your lead @spikanor11 https://github.com/patriciogonzalezvivo/ada/commit/5f271990a2beef77cde0e928bfc194273204e574

Thanks again

**Comment by irncat** [comment]
glad to be of help
